// ---------------------------------------------------------------------------
// 🍃 JetLeaf Framework - https://jetleaf.hapnium.com
//
// Copyright © 2025 Hapnium & JetLeaf Contributors. All rights reserved.
//
// This source file is part of the JetLeaf Framework and is protected
// under copyright law. You may not copy, modify, or distribute this file
// except in compliance with the JetLeaf license.
//
// For licensing terms, see the LICENSE file in the root of this project.
// ---------------------------------------------------------------------------
// 
// 🔧 Powered by Hapnium — the Dart backend engine 🍃

import 'enums/log_level.dart';
import 'enums/log_type.dart';
import 'log_printer.dart';
import 'models/log_config.dart';
import 'models/log_record.dart';
import 'printers/flat_printer.dart';
import 'printers/flat_structured_printer.dart';
import 'printers/fmt_printer.dart';
import 'printers/hybrid_printer.dart';
import 'printers/prefix_printer.dart';
import 'printers/pretty_printer.dart';
import 'printers/pretty_structured_printer.dart';
import 'printers/simple_printer.dart';

/// {@template application_log_listener}
/// A listener interface for reacting to logging events within an application.
///
/// The [TracingListener] interface allows you to observe and respond to log messages
/// generated by instances of [TracingListener]. This is useful for implementing
/// custom log processing, such as writing logs to:
///
/// - The console (standard output)
/// - External log files
/// - Remote logging services (e.g., Datadog, Sentry)
/// - In-memory dashboards or UIs
///
/// ### How to Implement
///
/// To respond to logs, implement this interface and override [onLog]:
///
/// ```dart
/// class ConsoleLogListener implements TracingListener {
///   @override
///   void onLog(LogLevel level, DateTime timestamp, String message, String tag) {
///     print('[$timestamp][$tag][$level] $message');
///   }
/// }
/// ```
///
/// ### Integration with Logger Factory
///
/// Register the listener with a logger:
///
/// ```dart
/// final logger = MyLoggerFactory("DatabaseService");
/// logger.registerListener(ConsoleLogListener());
///
/// logger.add(LogLevel.info, "Database connection established.");
/// ```
///
/// This enables a plug-and-play model where multiple listeners can be registered and
/// independently respond to log events.
///
/// {@endtemplate}
abstract class LoggingListener {
  final LogLevel _level;
  final LogPrinter _printer;
  final void Function(String)? _output;

  final String _name;

  LoggingListener({
    LogLevel level = LogLevel.INFO,
    LogPrinter? printer,
    LogType type = LogType.SIMPLE,
    void Function(String)? output,
    String name = "",
    LogConfig? config,
  }) : _level = level, 
    _printer = printer ?? _getPrinter(type, config ?? LogConfig()), 
    _output = output, 
    _name = name;

  static LogPrinter _getPrinter(LogType type, LogConfig config) {
    switch (type) {
      case LogType.PRETTY:
        return PrettyPrinter(config: config);
      case LogType.PRETTY_STRUCTURED:
        return PrettyStructuredPrinter(config: config);
      case LogType.FLAT:
        return FlatPrinter(config: config);
      case LogType.FLAT_STRUCTURED:
        return FlatStructuredPrinter(config: config);
      case LogType.PREFIX:
        return PrefixPrinter(config: config);
      case LogType.FMT:
        return FmtPrinter(config: config);
      case LogType.HYBRID:
        return HybridPrinter(config: config);
      case LogType.SIMPLE:
        return SimplePrinter(config: config);
    }
  }

  /// Called when a new log entry is emitted by a logger.
  ///
  /// This method provides complete context about the log event, including:
  /// - [level]: the severity or type of the log (e.g., info, error, debug)
  /// - [timestamp]: the exact time the log entry was recorded
  /// - [message]: the textual content of the log
  /// - [tag]: the name or label of the logger that emitted the message
  ///
  /// This method is called immediately after the message is stored in the logger’s
  /// internal buffer, allowing real-time response.
  ///
  /// ### Example
  /// ```dart
  /// void onLog(LogLevel level, DateTime timestamp, String message, String tag) {
  ///   sendToRemoteServer({
  ///     'level': level.name,
  ///     'time': timestamp.toIso8601String(),
  ///     'source': tag,
  ///     'log': message,
  ///   });
  /// }
  /// ```
  void onLog(LogLevel level, dynamic message, {String? tag, Object? error, StackTrace? stackTrace}) {
    if (!_level.isEnabledFor(level)) return;

    final record = LogRecord(
      level,
      message.toString(),
      loggerName: (tag ?? _name).replaceAll("[", "").replaceAll("]", ""),
      error: error,
      stackTrace: stackTrace,
    );

    final lines = _printer.log(record);
    final outputFn = _output ?? _defaultOutput;
    
    for (final line in lines) {
      outputFn(line);
    }
  }

  void _defaultOutput(String message) {
    print(message);
  }
}

/// {@template leaf_logger_listener}
/// A default implementation of [LoggingListener] that outputs logs to the console.
///
/// [JetLeafLoggingListener] provides a simple and human-readable logging mechanism
/// by printing log messages to the standard output (`stdout`). Each log entry is timestamped,
/// tagged, and categorized by [LogLevel].
///
/// This listener is ideal for:
/// - Development and debugging environments
/// - Local testing
/// - Simple CLI applications
///
/// ### Output Format
/// Logs are printed in the following format:
///
/// ```text
/// [2025-06-18 14:22:01.534][MyService][info] Service started successfully.
/// [2025-06-18 14:22:05.882][Database][error] Connection failed: Timeout
/// ```
///
/// ### Example Usage
///
/// ```dart
/// final logger = MyCustomLogger('Database');
/// final listener = DefaultApplicationLogListener();
///
/// logger.add(LogLevel.error, 'Connection failed');
/// 
/// // Somewhere internally, the listener gets notified:
/// listener.onLog(LogLevel.error, DateTime.now(), 'Connection failed', 'Database');
/// ```
///
/// ### Integration with Logging System
/// To use this with a custom logger or broadcasting mechanism:
///
/// ```dart
/// final listener = DefaultApplicationLogListener();
///
/// void broadcastLog(LogLevel level, String message, String tag) {
///   final now = DateTime.now();
///   listener.onLog(level, now, message, tag);
///   // other listeners can also be notified here
/// }
/// ```
///
/// {@endtemplate}
final class JetLeafLoggingListener extends LoggingListener {
  /// {@macro leaf_logger_listener}
  JetLeafLoggingListener({
    super.level,
    super.printer,
    super.type,
    super.output,
    super.name,
    super.config,
  });
}